version: 2
jobs:
  build:
    working_directory: ~/john/drive.vote
    parallelism: 1
    shell: /bin/bash --login
    
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      
    docker:
    - image: johnmcgrath/drivevote_web:add_git
    - image: postgres:10.5-alpine
    
    steps:
      
    - checkout
    
    - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
    
    - restore_cache:
        keys:
        # This branch if available
        - v1-dep-{{ .Branch }}-
        # Default branch if not
        - v1-dep-master-
        # Any branch if there are none on the default branch - this should be unnecessary if you have your default branch configured correctly
        - v1-dep-
          
    # Uncomment if at some point we need npm installed to run tests
    # - run: if [ -z "${NODE_ENV:-}" ]; then export NODE_ENV=test; fi
    # - run: export PATH="~/john/drive.vote/node_modules/.bin:$PATH"
    # - run: npm install
    
    - run: echo -e "export RAILS_ENV=test\nexport RACK_ENV=test" >> $BASH_ENV
    
    - run: 'bundle check --path=vendor/bundle || bundle install --path=vendor/bundle
        --jobs=4 --retry=3 '
        
    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ epoch }}
        paths:
        - vendor/bundle
        - ~/.bundle
        - ./node_modules

    - run:
        command: bundle exec rake db:create db:schema:load --trace
        environment:
          RAILS_ENV: test
          RACK_ENV: test
          
    - run:
        command: bundle exec rspec --color --require spec_helper --format progress spec
        environment:
          RAILS_ENV: test
          RACK_ENV: test
          
    # Teardown
    #   If you break your build into multiple jobs with workflows, you will probably want to do the parts of this that are relevant in each
    # Save test results
    - store_test_results:
        path: /tmp/circleci-test-results
    # Save artifacts
    - store_artifacts:
        path: /tmp/circleci-artifacts
    - store_artifacts:
        path: /tmp/circleci-test-results
